name: sportly
description: BSc thesis project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  bloc_test: ^9.1.0
  calendar_view: ^1.0.0
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_chat_ui: ^1.6.6
  flutter_datetime_picker: ^1.5.1
  flutter_hooks: 0.18.5+1
  flutter_localizations: 
    sdk: flutter  
  flutter_native_splash: 2.2.10+1
  flutter_svg: ^1.1.5
  freezed: ^2.1.1
  gap: ^2.0.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  hooked_bloc: 1.0.2
  injectable: ^1.5.3
  json_serializable: ^6.5.2
  loader_overlay: ^2.1.0
  mocktail: ^0.3.0
  path_provider: ^2.0.11
  pinput: ^2.2.16
  retrofit: ^3.3.1
  rxdart: ^0.27.5
  salomon_bottom_bar: ^3.3.1
  uuid: ^3.0.6
  
dev_dependencies: 
  auto_route_generator: ^5.0.3
  build_runner: ^2.2.1
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  integration_test:
    sdk: flutter
  retrofit_generator: ^4.2.0

dependency_overrides:
  analyzer: ^4.2.0

flutter_icons:
  image_path: "assets/images/logo/logo-white.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
  assets:
    - assets/translations/
    - assets/images/logo/
    - assets/images/icons/
    - assets/mocks/teams/
