// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4AyMgGyLADqbwR8HBcIKGUy5eAtTu3M',
    appId: '1:974596240161:android:f74fdc8432b61ba0180460',
    messagingSenderId: '974596240161',
    projectId: 'sportly-2253a',
    storageBucket: 'sportly-2253a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAxAjxmdZ-fersKOPttYEKvgKasDdHvfo',
    appId: '1:974596240161:ios:76df3de0960064f2180460',
    messagingSenderId: '974596240161',
    projectId: 'sportly-2253a',
    storageBucket: 'sportly-2253a.appspot.com',
    androidClientId: '974596240161-74oupc0i1r89cjr1qcrnhseao895v95s.apps.googleusercontent.com',
    iosClientId: '974596240161-k8hq6lqsd4df407ighj6rnr29sevb233.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportly',
  );
}
